# Generated by Django 5.1.4 on 2025-01-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.CharField(
                default="https://img.freepik.com/free-photo/funny-monkey-with-hat-studio_23-2150844087.jpg?semt=ais_hybrid",
                max_length=2083,
            ),
            preserve_default=False,
        ),
    ]
